version: '3.8'

services:
  sql_server:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "ChangeMe"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    restart: always
    volumes:
      - D:\Docker\Volumes:/var/opt/mssql/data
