version: '3.8'

services:
  web:
    image: nginx:latest
    container_name: nginx_web_server
    volumes:
      - ./src:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./fastcgi-php.conf:/etc/nginx/snippets/fastcgi-php.conf
    ports:
      - "8081:80"
    networks:
      - webnet
    restart: always

  php:
    image: php:8.1-fpm
    container_name: php_fpm
    volumes:
      - ./src:/var/www/html
    networks:
      - webnet
    entrypoint: >
      sh -c "
      apt-get update &&
      apt-get install -y libpq-dev &&
      docker-php-ext-install pdo pdo_pgsql &&
      php-fpm
      "
    restart: always

networks:
  webnet:
    driver: bridge
