version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Banco123

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
      - 27017:27017
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: hola 
      ME_CONFIG_MONGODB_ADMINPASSWORD: Banco123 
      ME_CONFIG_MONGODB_URL: mongodb://root:Banco123@mongo:27017/
