version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    user: "0:0"
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - Z:\jenkins_home:/var/jenkins_home
      - ./init.groovy.d:/var/jenkins_home/init.groovy.d  # Mount the initialization script directory
      - D:\Repos\Teclab\Programacion_web\APIs:/mnt/d/Repos/Teclab/Programacion_web/APIs:rw  # Ensure read-write access
    environment:
      - JENKINS_OPTS=--prefix=/jenkins
      - JENKINS_ADMIN_PASSWORD=your_password  # Replace with your desired password
    cap_add:
      - NET_ADMIN
    networks:
      - bridge
    restart: always

networks:
  bridge:
    driver: bridge
