version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ChangeMe
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - D:\Docker\Volumes\pg_data:/var/lib/postgresql/data
